# Generated by Django 2.2.6 on 2019-10-23 07:08

from django.db import migrations, models
import django.db.models.deletion
import newspaper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('published_at', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('news_source', models.URLField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='newspaper.Category')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('moderated', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('web_site', models.URLField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.News')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.Review')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='newspaper.Tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=newspaper.models.image_folder)),
                ('image_source', models.URLField(blank=True, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.News')),
            ],
        ),
    ]
